# Generated by Django 4.2.7 on 2023-11-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennisclub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='race',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='type',
            new_name='prenom',
        ),
    ]
