# Generated by Django 4.2.7 on 2023-11-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisclub', '0003_alter_character_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='place',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
