# Generated by Django 4.2.7 on 2023-11-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisclub', '0004_equipement_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='capa',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.ImageField(upload_to='static/image/'),
        ),
    ]
